In [3]:
import pandas as pd
import shutil

In [4]:
raw = pd.read_csv("DATA/RAW DATA/Tuberculosis Trends.csv")
print(raw)

        Country         Region  Income_Level  Year  TB_Cases  TB_Deaths  \
0     Indonesia           Asia  Upper-Middle  2002     14128       3846
1        Brazil  North America  Lower-Middle  2017      1069        342
2       Nigeria  South America          High  2006      2473       6316
3        Russia         Africa  Lower-Middle  2014     36090       6420
4     Indonesia         Europe  Upper-Middle  2020     33538       4910
...         ...            ...           ...   ...       ...        ...
2995     Russia         Africa  Lower-Middle  2018     26021       2096
2996     Russia           Asia  Lower-Middle  2014     37172       3194
2997      India         Europe           Low  2011     15967       3271
2998   Pakistan         Europe          High  2020     32519       5114
2999  Indonesia           Asia  Upper-Middle  2009     10919       9495

      TB_Incidence_Rate  TB_Mortality_Rate  TB_Treatment_Success_Rate  \
0                150.58              18.99                      54.52
1                167.80              44.20                      88.19
2                285.77               6.52                      64.55
3                146.46              24.86                      69.77
4                 56.87              10.52                      64.57
...                 ...                ...                        ...
2995             242.90               8.94                      55.26
2996             361.96              42.03                      87.40
2997             175.07              40.04                      80.34
2998             316.16               8.48                      50.31
2999             254.20              18.83                      78.25

      Drug_Resistant_TB_Cases  ...  GDP_Per_Capita  \
0                        3977  ...           25516
1                        4179  ...           26300
2                        4961  ...           30771
3                        4012  ...           35730
4                        2342  ...           38391
...                       ...  ...             ...
2995                     1420  ...           18921
2996                     1147  ...           42422
2997                     4676  ...            1743
2998                     1578  ...           56769
2999                     4482  ...           58376

      Health_Expenditure_Per_Capita  Urban_Population_Percentage  \
0                              3180                        50.49
1                              5529                        24.06
2                              1703                        81.77
3                              8354                        42.19
4                              8024                        64.97
...                             ...                          ...
2995                           6286                        51.26
2996                           2530                        23.09
2997                            607                        22.81
2998                           3536                        86.03
2999                            211                        76.74

      Malnutrition_Prevalence  Smoking_Prevalence  TB_Doctors_Per_100K  \
0                       28.84               22.90                 4.10
1                       28.65               33.79                 8.18
2                       38.69                6.63                 2.26
3                       20.38               15.00                 8.33
4                       39.28               18.00                 6.60
...                       ...                 ...                  ...
2995                    12.82               30.33                 1.11
2996                    22.61               11.46                 3.51
2997                    39.17               39.14                 6.49
2998                    45.81               17.83                 5.24
2999                    49.94               19.42                 2.50

      TB_Hospitals_Per_Million  Access_To_Health_Services  \
0                        15.46                      52.38
1                         3.06                      46.95
2                         4.95                      40.88
3                        13.68                      62.20
4                         4.35                      53.88
...                        ...                        ...
2995                      4.53                      85.44
2996                      9.58                      64.52
2997                     19.83                      78.64
2998                     18.67                      65.16
2999                      7.37                      98.48

      BCG_Vaccination_Coverage  HIV_Testing_Coverage
0                        95.87                 88.39
1                        63.78                 35.60
2                        68.91                 77.81
3                        71.14                 84.91
4                        55.11                 49.89
...                        ...                   ...
2995                     63.19                 33.62
2996                     63.58                 29.94
2997                     81.42                 26.08
2998                     93.22                 75.91
2999                     80.25                 65.25

[3000 rows x 22 columns]

In [5]:
# select columns to drop
print(raw.columns)

Index(['Country', 'Region', 'Income_Level', 'Year', 'TB_Cases', 'TB_Deaths',
       'TB_Incidence_Rate', 'TB_Mortality_Rate', 'TB_Treatment_Success_Rate',
       'Drug_Resistant_TB_Cases', 'HIV_CoInfected_TB_Cases', 'Population',
       'GDP_Per_Capita', 'Health_Expenditure_Per_Capita',
       'Urban_Population_Percentage', 'Malnutrition_Prevalence',
       'Smoking_Prevalence', 'TB_Doctors_Per_100K', 'TB_Hospitals_Per_Million',
       'Access_To_Health_Services', 'BCG_Vaccination_Coverage',
       'HIV_Testing_Coverage'],
      dtype='object')

In [6]:
# Filter the original DataFrame raw to keep only the columns relevant to tuberculosis and its risk factors, columns needed for this analysis.
clean = raw.loc[:, ['Country', 'Year', 'TB_Cases', 'TB_Deaths', 'TB_Incidence_Rate', 'TB_Mortality_Rate',
                  'Population',  'Urban_Population_Percentage', 'Malnutrition_Prevalence', 'Smoking_Prevalence', 
                  'TB_Doctors_Per_100K', 'Access_To_Health_Services', 'BCG_Vaccination_Coverage']]
print(clean)

        Country  Year  TB_Cases  TB_Deaths  TB_Incidence_Rate  \
0     Indonesia  2002     14128       3846             150.58
1        Brazil  2017      1069        342             167.80
2       Nigeria  2006      2473       6316             285.77
3        Russia  2014     36090       6420             146.46
4     Indonesia  2020     33538       4910              56.87
...         ...   ...       ...        ...                ...
2995     Russia  2018     26021       2096             242.90
2996     Russia  2014     37172       3194             361.96
2997      India  2011     15967       3271             175.07
2998   Pakistan  2020     32519       5114             316.16
2999  Indonesia  2009     10919       9495             254.20

      TB_Mortality_Rate  Population  Urban_Population_Percentage  \
0                 18.99    11840158                        50.49
1                 44.20   412757119                        24.06
2                  6.52  1246189339                        81.77
3                 24.86   987178400                        42.19
4                 10.52   672508232                        64.97
...                 ...         ...                          ...
2995               8.94   733007799                        51.26
2996              42.03  1394319641                        23.09
2997              40.04   623950718                        22.81
2998               8.48   952999575                        86.03
2999              18.83   617718219                        76.74

      Malnutrition_Prevalence  Smoking_Prevalence  TB_Doctors_Per_100K  \
0                       28.84               22.90                 4.10
1                       28.65               33.79                 8.18
2                       38.69                6.63                 2.26
3                       20.38               15.00                 8.33
4                       39.28               18.00                 6.60
...                       ...                 ...                  ...
2995                    12.82               30.33                 1.11
2996                    22.61               11.46                 3.51
2997                    39.17               39.14                 6.49
2998                    45.81               17.83                 5.24
2999                    49.94               19.42                 2.50

      Access_To_Health_Services  BCG_Vaccination_Coverage
0                         52.38                     95.87
1                         46.95                     63.78
2                         40.88                     68.91
3                         62.20                     71.14
4                         53.88                     55.11
...                         ...                       ...
2995                      85.44                     63.19
2996                      64.52                     63.58
2997                      78.64                     81.42
2998                      65.16                     93.22
2999                      98.48                     80.25

[3000 rows x 13 columns]

In [22]:
# # Sort the DataFrame by the 'Year' column in ascending order
clean = clean.sort_values(by='Year')
print(clean)

       Country  Year  TB_Cases  TB_Deaths  TB_Incidence_Rate  \
2936       USA  2000     48422       2601              69.39
2934     India  2000      6682       5982             465.13
2925     India  2000     37019       7158             389.34
52      Brazil  2000     44467       6668             225.78
2133  Pakistan  2000     12285       2408             288.43
...        ...   ...       ...        ...                ...
2944    Russia  2024      9059       7399             333.26
1192    Russia  2024     17479       9448             322.84
54     Nigeria  2024     49563       7522             133.70
2981    Brazil  2024     36056       5081             361.56
1199    Russia  2024      8803       1703             446.85

      TB_Mortality_Rate  Population  Urban_Population_Percentage  \
2936              41.97   547371029                        28.08
2934              25.82   826890713                        45.35
2925              45.66   249171176                        20.89
52                29.93   171433584                        68.31
2133              42.23  1322232591                        70.28
...                 ...         ...                          ...
2944               2.52  1291511383                        54.98
1192              39.65   184980706                        31.38
54                49.30  1131206505                        85.48
2981              37.74   514891476                        30.23
1199               4.32   763778512                        59.43

      Malnutrition_Prevalence  Smoking_Prevalence  TB_Doctors_Per_100K  \
2936                    27.02               34.13                 1.66
2934                     5.25               14.22                 8.04
2925                    34.68               35.94                 1.69
52                       5.08               16.31                 4.19
2133                    20.29               25.83                 3.80
...                       ...                 ...                  ...
2944                    25.41                5.06                 9.30
1192                    27.55                8.38                 6.64
54                      15.57               20.40                 7.08
2981                    27.53               33.60                 1.11
1199                    24.35               13.95                 7.79

      Access_To_Health_Services  BCG_Vaccination_Coverage
2936                      97.00                     71.54
2934                      65.53                     52.22
2925                      95.64                     94.83
52                        64.40                     95.80
2133                      59.29                     66.69
...                         ...                       ...
2944                      90.32                     77.99
1192                      86.82                     90.47
54                        93.49                     96.09
2981                      38.30                     54.83
1199                      30.88                     54.43

[3000 rows x 13 columns]

In [23]:
# Average duplicates for each country and year. To have each country appear once a year.
clean_TB_avg = clean.groupby(['Country', 'Year'], as_index=False).mean()
print(clean_TB_avg)

        Country  Year      TB_Cases    TB_Deaths  TB_Incidence_Rate  \
0    Bangladesh  2000  21836.700000  6025.000000         316.525500
1    Bangladesh  2001  18115.000000  4046.000000         341.376000
2    Bangladesh  2002  25808.666667  4261.000000         255.198889
3    Bangladesh  2003  24814.785714  3809.785714         327.180000
4    Bangladesh  2004  28415.400000  6035.500000         272.117000
..          ...   ...           ...          ...                ...
245         USA  2020  21129.500000  5269.200000         297.089000
246         USA  2021  21007.142857  3201.428571         285.974286
247         USA  2022  31407.600000  6023.866667         253.673333
248         USA  2023  27703.545455  6002.000000         246.024545
249         USA  2024  26832.916667  4297.666667         283.975000

     TB_Mortality_Rate    Population  Urban_Population_Percentage  \
0            22.286500  6.703438e+08                    51.016500
1            25.532000  7.016417e+08                    45.268000
2            20.453889  7.571083e+08                    57.120556
3            29.762143  6.784536e+08                    54.247857
4            28.816000  6.826866e+08                    56.943000
..                 ...           ...                          ...
245          30.186000  7.849409e+08                    60.090000
246          19.812857  9.580873e+08                    52.978571
247          26.543333  7.883010e+08                    55.515333
248          29.214545  7.060626e+08                    52.087273
249          24.186667  7.876782e+08                    48.050833

     Malnutrition_Prevalence  Smoking_Prevalence  TB_Doctors_Per_100K  \
0                  26.426500           22.523000             4.364000
1                  27.820000           26.418000             7.532000
2                  30.132222           19.652222             5.036667
3                  25.980714           21.926429             4.527857
4                  24.148000           22.011000             4.470000
..                       ...                 ...                  ...
245                28.018000           22.140000             4.110000
246                32.048571           25.894286             2.774286
247                22.657333           20.240667             5.432000
248                20.811818           23.162727             5.218182
249                25.278333           23.558333             4.706667

     Access_To_Health_Services  BCG_Vaccination_Coverage
0                    66.799000                 73.630000
1                    72.664000                 66.190000
2                    67.353889                 70.256111
3                    74.698571                 71.676429
4                    56.362000                 71.503000
..                         ...                       ...
245                  62.249000                 69.852000
246                  64.472857                 83.158571
247                  59.010667                 79.668667
248                  58.169091                 80.250000
249                  63.940000                 72.790833

[250 rows x 13 columns]

In [24]:
clean_TB_avg.head(50)

,Country,Year,TB_Cases,TB_Deaths,TB_Incidence_Rate,TB_Mortality_Rate,Population,Urban_Population_Percentage,Malnutrition_Prevalence,Smoking_Prevalence,TB_Doctors_Per_100K,Access_To_Health_Services,BCG_Vaccination_Coverage
0,Bangladesh,2000,21836.700000,6025.000000,316.525500,22.286500,6.703438e+08,51.016500,26.426500,22.523000,4.364000,66.799000,73.630000
1,Bangladesh,2001,18115.000000,4046.000000,341.376000,25.532000,7.016417e+08,45.268000,27.820000,26.418000,7.532000,72.664000,66.190000
2,Bangladesh,2002,25808.666667,4261.000000,255.198889,20.453889,7.571083e+08,57.120556,30.132222,19.652222,5.036667,67.353889,70.256111
3,Bangladesh,2003,24814.785714,3809.785714,327.180000,29.762143,6.784536e+08,54.247857,25.980714,21.926429,4.527857,74.698571,71.676429
4,Bangladesh,2004,28415.400000,6035.500000,272.117000,28.816000,6.826866e+08,56.943000,24.148000,22.011000,4.470000,56.362000,71.503000
5,Bangladesh,2005,22259.250000,6070.125000,341.090000,18.140000,6.689054e+08,51.105000,29.891250,19.772500,5.893750,66.307500,75.668750
6,Bangladesh,2006,28395.727273,4598.636364,170.503636,18.288182,5.535952e+08,61.144545,32.481818,23.274545,7.431818,59.257273,73.867273
7,Bangladesh,2007,26704.600000,4579.000000,228.026000,39.312000,6.823797e+08,57.954000,26.482000,24.852000,3.090000,65.132000,81.342000
8,Bangladesh,2008,22076.200000,4723.900000,237.882000,24.659000,6.529588e+08,51.200000,28.310000,24.083000,4.532000,65.711000,75.597000
9,Bangladesh,2009,27635.200000,4816.000000,229.970000,25.220667,7.951254e+08,54.677333,28.225333,21.351333,4.624000,74.249333,71.852667
10,Bangladesh,2010,16888.461538,4862.538462,275.292308,28.348462,7.255698e+08,50.661538,24.907692,19.400000,5.753077,63.353846,79.385385
11,Bangladesh,2011,34750.285714,5996.714286,292.801429,29.535714,6.760566e+08,47.177143,31.507143,26.738571,5.002857,58.262857,70.595714
12,Bangladesh,2012,23379.823529,4382.411765,231.019412,26.834118,7.173598e+08,50.584118,29.785882,21.491176,5.301765,70.069412,79.433529
13,Bangladesh,2013,23717.250000,5115.250000,229.281250,29.503750,8.312470e+08,54.205000,30.805000,22.787500,3.917500,58.842500,79.292500
14,Bangladesh,2014,34301.000000,5891.000000,316.894000,24.331000,4.078652e+08,43.745000,31.278000,18.956000,4.828000,61.651000,79.155000
15,Bangladesh,2015,21815.615385,4090.923077,202.485385,26.683077,7.187565e+08,58.868462,25.455385,18.704615,3.134615,69.598462,68.553077
16,Bangladesh,2016,29977.909091,5928.454545,177.268182,24.892727,8.021735e+08,54.934545,24.794545,17.783636,4.078182,56.480909,79.776364
17,Bangladesh,2017,18499.307692,5077.538462,199.212308,24.463077,8.198111e+08,53.046923,25.883846,21.630769,6.166154,67.144615,79.908462
18,Bangladesh,2018,26116.714286,3207.285714,189.331429,19.462857,8.651215e+08,55.981429,25.451429,24.294286,6.440000,53.951429,69.221429
19,Bangladesh,2019,28913.357143,4759.000000,255.770000,29.930714,8.317784e+08,55.671429,27.910000,22.074286,5.455000,56.873571,73.986429
20,Bangladesh,2020,28978.500000,5059.750000,323.824167,24.856667,5.091392e+08,62.711667,28.172500,20.702500,5.070000,64.040000,69.010833
21,Bangladesh,2021,25534.315789,4895.473684,274.394737,28.481053,8.028894e+08,60.470526,28.188947,23.017368,4.924737,68.591579,76.451053
22,Bangladesh,2022,26669.444444,4579.777778,195.448889,30.487778,7.167377e+08,60.633333,25.384444,22.545556,5.538889,69.415556,68.393333
23,Bangladesh,2023,22413.875000,5703.125000,230.613750,16.765000,6.071460e+08,52.158750,26.223750,25.487500,7.475000,63.177500,72.193750
24,Bangladesh,2024,24516.437500,4711.750000,231.082500,29.072500,6.514200e+08,53.096250,20.829375,26.113125,5.373750,64.192500,77.506875
25,Brazil,2000,26469.928571,4715.071429,264.630714,25.564286,6.243100e+08,53.610714,26.952857,23.152143,4.580714,65.399286,72.300714
26,Brazil,2001,27111.200000,5496.066667,222.940667,22.799333,5.773580e+08,57.509333,29.274000,20.102667,4.538000,59.501333,72.997333
27,Brazil,2002,25070.307692,4635.076923,224.391538,26.070000,6.154342e+08,52.996154,24.186923,16.760769,4.943846,58.539231,74.576154
28,Brazil,2003,26293.800000,4056.400000,224.887000,21.379000,3.593807e+08,52.546000,29.837000,20.646000,3.956000,67.115000,71.201000
29,Brazil,2004,26121.500000,5998.700000,211.456000,32.323000,8.924601e+08,54.511000,33.670000,18.320000,4.539000,71.741000,77.079000
30,Brazil,2005,25923.812500,5550.750000,248.081875,26.840625,6.703677e+08,57.294375,29.585000,19.726875,2.998125,60.341875,81.502500
31,Brazil,2006,18239.300000,4474.800000,276.510000,28.467000,7.049094e+08,58.803000,23.078000,22.257000,4.328000,62.141000,72.674000
32,Brazil,2007,33859.200000,1376.600000,268.466000,22.506000,5.720187e+08,43.020000,22.040000,21.032000,5.386000,50.022000,80.334000
33,Brazil,2008,20199.833333,5521.000000,249.905833,22.847500,6.911356e+08,53.842500,20.476667,22.645833,4.070000,63.502500,71.757500
34,Brazil,2009,32976.470588,4062.117647,225.956471,26.452353,7.712310e+08,59.845294,27.225882,21.856471,5.812353,75.715882,71.732353
35,Brazil,2010,24109.692308,4944.076923,227.804615,21.759231,6.156093e+08,59.296923,30.213846,23.964615,4.736923,69.896923,77.715385
36,Brazil,2011,26077.111111,4941.222222,190.011111,21.807778,5.346975e+08,65.241111,26.291111,17.718889,4.188889,55.557778,79.612222
37,Brazil,2012,28568.545455,6954.000000,281.848182,23.549091,5.212827e+08,53.022727,31.350000,19.010000,5.082727,63.679091,83.715455
38,Brazil,2013,30050.000000,4664.800000,267.101000,25.124000,7.473109e+08,45.781000,22.959000,23.159000,7.133000,54.344000,75.715000
39,Brazil,2014,22726.750000,5689.625000,301.955000,30.737500,8.936823e+08,57.822500,39.560000,13.136250,5.201250,68.368750,76.842500
40,Brazil,2015,25459.000000,5839.900000,335.548000,18.933000,7.061847e+08,61.553000,23.565000,16.391000,4.661000,64.915000,76.103000
41,Brazil,2016,23216.642857,4966.714286,280.672143,25.521429,8.537891e+08,49.781429,26.844286,18.369286,5.787857,64.075000,70.485714
42,Brazil,2017,19035.076923,4101.153846,269.372308,30.956923,7.483789e+08,54.926923,21.224615,22.529231,5.243077,55.949231,77.780000
43,Brazil,2018,26776.230769,5231.384615,237.576923,23.983077,6.714539e+08,58.426154,33.957692,20.829231,5.793077,64.763077,77.563077
44,Brazil,2019,23554.533333,5416.733333,228.690000,31.845333,7.448698e+08,50.244000,27.246000,27.062000,6.053333,58.745333,74.321333
45,Brazil,2020,24487.857143,6765.857143,241.300714,29.460714,7.138753e+08,60.505000,18.880000,22.050714,5.600000,56.043571,74.513571
46,Brazil,2021,22244.666667,5164.666667,289.960000,24.561111,6.180228e+08,61.528889,25.470000,18.046667,5.915556,58.885556,77.198889
47,Brazil,2022,27253.428571,5115.785714,223.823571,30.327857,8.025549e+08,41.559286,28.381429,23.596429,5.922143,62.445714,74.559286
48,Brazil,2023,18029.666667,5752.333333,145.336667,16.943333,5.680213e+08,47.543333,28.160000,28.503333,6.570000,53.330000,78.523333
49,Brazil,2024,17577.538462,5702.615385,277.889231,26.717692,6.365689e+08,45.530000,25.966154,19.550769,5.627692,61.129231,67.473846

In [25]:
#clean_TB_avg to csv
clean_TB_avg.to_csv('clean-TB-data.csv', index=False)

In [26]:
# Load the clean-TB-data.csv to DATA/CLEAN DATA
source = "clean-TB-data.csv"
destination = "DATA/CLEAN DATA"
shutil.move(source, destination)

'DATA/CLEAN DATA\\clean-TB-data.csv'